#!/usr/bin/env bash

# WORKDIR=/autograder

# EMAIL is for unique identifier for the student so then we can handle multiple requests
# at once by creating a new directory for each student submission
EMAIL=$(grep -o '"email":\s*"[^"]*' submission_metadata.json | sed 's/"email": "\(.*\)@.*/\1/')
cp /autograder/submission/calculator.py /autograder/source/calculator.py

cd /autograder/source

cp id_ed25519 ~/.ssh/
cp config ~/.ssh/

chmod 600 /root/.ssh/id_ed25519
scp -r /autograder/ oed1:~/autograder_${EMAIL}
ssh -o StrictHostKeyChecking=no oed1 "cd ~/autograder_${EMAIL}/source && ./real_run_autograder"
exit
scp -r oed1:~/autograder_${EMAIL}/ /autograder/
# ssh -o StrictHostKeyChecking=no oed1 "rm -rf ~/autograder_${EMAIL}"
# exit
