#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/calculator.py /autograder/source/calculator.py

cd /autograder/source

mv id_ed25519 ~/.ssh/
chmod 600 /root/.ssh/id_ed25519
scp -r /autograder/ ubuntu@199.94.60.56:~/
ssh -o StrictHostKeyChecking=no ubuntu@199.94.60.56 "cd ~/autograder && ./real_run_autograder"
exit
python3 run_tests.py
