#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/calculator.py /autograder/source/calculator.py

cd /autograder/source

cp id_ed25519 ~/.ssh/
cp config ~/.ssh/

chmod 600 /root/.ssh/id_ed25519
scp -r /autograder/ oed1:~/
ssh -o StrictHostKeyChecking=no oed1 "cd ~/autograder/source && ./real_run_autograder"
exit
scp -r oed1:~/autograder/ /autograder/
